name: sample-rails
services:
- name: web
  github:
    repo: snormore/sample-rails
    branch: master
    deploy_on_push: true
  envs:
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: RAILS_SERVE_STATIC_FILES
    value: '1'
  - key: RAILS_ENV
    value: production
  # The RAILS_MASTER_KEY environment variable is encrypted with a key specific
  # to your application. You must first submit your spec with it unencrypted,
  # and the platform will encrypt in-place to look similar to what you see below
  # with the EV prefix.
  - key: RAILS_MASTER_KEY
    value: secret
    #value: EV[1:xWTjge/c/Oe6kPy0/AFs916m3LcXMzWO:/RoXzy12ATYCexS2h50jI2tJFTQ9+E415Yldtl4l5Ua0UeHrERbI6epjcnehWKZZ]
    type: SECRET
  run_command: bin/rails server
jobs:
- name: migrate
  kind: PRE_DEPLOY
  github:
    repo: snormore/sample-rails
    branch: master
    deploy_on_push: true
  envs:
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: RAILS_ENV
    value: production
  run_command: bin/rails db:migrate
databases:
- name: db
  engine: PG
  version: "12"
